### ISSUE TITLE
Latest release (0.1.3) doesn't work with Scala 2.13.9+

### ISSUE THREAD

**Issue by Jaystified** [lightbend-labs/scala-rewrites#182]
0.1.3 has been released over two years ago and doesn't work with latest Scala 2 versions.

Although this repo keeps getting updates and the problem has been solved in the main branch for a while, compiling it locally as a dependency is inconvenient and a new release is preferable.

Is there a chance for a new release in the near future?

**Comment by SethTisue** [comment]
Sadly, this repo is currently without anyone really overseeing it and driving it forward. So for example, it would be nice if a volunteer could try and figure out how to get https://github.com/scala/scala-rewrites/pull/181 through.

But yes, regardless, we should roll a release with whatever we currently have, as a new baseline. I've pushed a tag: https://github.com/scala/scala-rewrites/releases/tag/v0.1.4

But the release build failed:

```
[info] gpg: no default secret key: No secret key
[info] gpg: signing failed: No secret key
```

I'll look into that next.

**Comment by SethTisue** [comment]
I've transferred the repo to the lightbend-labs org, to better reflect the maintenance status.

**Comment by SethTisue** [comment]
okay, https://github.com/lightbend-labs/scala-rewrites/releases/tag/v0.1.4 worked once I added the needed secrets to the repository, as per the sbt-ci-release documentation

@Jaystified could you (or could anyone watching this repo) give the release a try and see if it resolves the issue...?

**Comment by Jaystified** [comment]
Thanks @SethTisue !
I've given v0.1.4 a go and it seems to work. It sure does spit out a lot of warnings, though (probably due to #181 as you've mentioned)...

**Comment by SethTisue** [comment]
How about 0.1.5? (It's on its way to Maven Central, should be there in 15 minutes or so.)

**Comment by Jaystified** [comment]
Yes, thanks!  Scala 2.13.11 + scalafix 0.11.0 + scala-rewrites v0.1.5 does allow running scalafix without any errors that I can see.
